site_name: CayenneIMP Encoder/Decoder

theme:
    name: material
    palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
plugins:
  - mkdoxy:
      projects:
        Doxygen: # name of project must be alphanumeric + numbers (without spaces)
          src-dirs: src/ # path to source code (support multiple paths separated by space) => INPUT
          full-doc: True # if you want to generate full documentation
          doxy-cfg: # standard doxygen configuration (key: value)
            FILE_PATTERNS: "*.cpp *.hpp*" # specify file patterns to filter out
            RECURSIVE: True # recursive search in source directories
nav:
  - Home: "index.md"
  - 'Design choices': "design_choices.md"
  - 'Getting started': "getting_started.md"
  - 'Examples': "examples.md"
  - 'Tests': "tests.md"
  - 'Library API': "api.md"
  - Doxygen:
    - "Complete Overview": "Doxygen/namespaceCayenneLPP.md"
    - "Struct and Union List": "Doxygen/annotated.md"
    - "CayenneLPP Class": "Doxygen/classCayenneLPP_1_1CayenneLPP.md"
    - "CayenneLPP Helper functions": "Doxygen/namespace_member_functions.md"
    - "CayenneLPP.hpp File": "Doxygen/CayenneLPP_8hpp.md"
    - "CayenneTypes.hpp File": "Doxygen/CayenneTypes_8hpp.md"
